name: Basic Workflow

on: push

jobs: 
    echo-hello:
        runs-on: ubuntu-latest

        steps:
            - name:  Echo Hello
              run: echo "Hello, World!"

    echo-goodbye:
        runs-on: ubuntu-latest

        steps:
            - name:  Echo Goodbye
              run: echo "Goobye, World!"
